import React from 'react'
import { Route, Routes } from 'react-router-dom'
import {CarPage} from '../Pages/CartegoryPages/CarPage'
import {CommericalVPage} from '../Pages/CartegoryPages/CommericalVPage'
import {HouseSalePage} from '../Pages/CartegoryPages/HouseSalePage'
import {ScootersPage} from '../Pages/CartegoryPages/ScootersPage'
import {MotorcyclePage} from '../Pages/CartegoryPages/MotorcyclePage'
import {HouseRentPage} from '../Pages/CartegoryPages/HouseRentPage'
import Dropdown from './Dropdown'
